on:
  pull_request:
    branches:
      - main

jobs:
  check_lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install Linter and Formatter Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit black isort
      - name: Run Lint
        run: |
          pre-commit run --all-files
      - name: Install Repo Dependencies
        run: |
          pip install -e .
      - name: Run Unit Tests
        run: |
          python -m unittest discover -s test